version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA}:/data
    #     - ${PORTAINER_CERT}:/certs/portainer.crt
    #     - ${PORTAINER_KEY}:/certs/portainer.key
    network_mode: change-me #docker network to join
    ports:
      - ${PORT}:9443
    restart: always
